name: CI

# When a pull request is opened, synchronized, or reopened,
# This workflow will checkout the repo, install dependancies, and run a prettier check.
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format-files:
    runs-on: ubuntu-latest
    name: bun format:check
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Format All Files with Prettier
        run: bun format:check
